import type { HookEventType, HookNodeId } from "./types"

export const EVENT_TOTAL_ORDER: Record<HookEventType, HookNodeId[]> = {
  "chat.message": [
    "internal:session-agent-tracking:chat.message",
    "internal:first-message-variant:chat.message",
    "think-mode:chat.message",
    "keyword-detector:chat.message",
    "sisyphus-contextual-injector:chat.message",
    "bridge:claude-code-hooks:chat.message",
    "internal:governance-user-prompt:chat.message",
    "session-handoff:chat.message",
    "auto-slash-command:chat.message",
    "start-work:chat.message",
    "swarm-from-plan:chat.message",
    "work-orchestrator:chat.message",
    "pre-completion-verification:chat.message",
    "internal:ralph-loop-template:chat.message",
  ],
  "chat.headers": [
    "internal:copilot-anthropic-beta:chat.headers",
    "internal:copilot-subagent-initiator:chat.headers",
  ],
  "user.prompt.submit": [
    "internal:user-memory:user.prompt.submit",
    "internal:org-memory:user.prompt.submit",
    "session-handoff:user.prompt.submit",
  ],
  "command.execute.before": [
    "auto-slash-command:command.execute.before",
  ],
  "shell.env": [
    "internal:non-interactive-env:shell.env",
  ],
  "tool.execute.before": [
    "question-label-truncator:tool.execute.before",
    "delegation-block-subagent-question:tool.execute.before",
    "write-existing-file-guard:tool.execute.before",
    "internal:user-memory:tool.execute.before",
    "internal:org-memory:tool.execute.before",
    "runtime-tracker:tool.execute.before",
    "bridge:claude-code-hooks:tool.execute.before",
    "non-interactive-env:tool.execute.before",
    "comment-checker:tool.execute.before",
    "directory-agents-injector:tool.execute.before",
    "directory-readme-injector:tool.execute.before",
    "rules-injector:tool.execute.before",
    "prometheus-md-only:tool.execute.before",
    "work-orchestrator:tool.execute.before",
    "sisyphus-contextual-injector:tool.execute.before",
    "delegation-validate-decision:tool.execute.before",
    "sisyphus-junior-notepad:tool.execute.before",
    "tmux-parallel-agents:tool.execute.before",
    "swarm-agent:tool.execute.before",
    "conditional-rules:tool.execute.before",
    "context-manifest-injector:tool.execute.before",
    "internal:task-tools-sanitizer:tool.execute.before",
    "internal:ralph-loop-slash:tool.execute.before",
    "internal:stop-continuation-slash:tool.execute.before",
    "internal:governance-pre-tool:tool.execute.before",
    "silent-tool-output:tool.execute.before",
  ],
  "tool.execute.after": [
    "work-orchestrator:tool.execute.after",
    "bridge:claude-code-hooks:tool.execute.after",
    "anti-slop-enforcer:tool.execute.after",
    "silent-tool-output:tool.execute.after",
    "tool-output-truncator:tool.execute.after",
    "runtime-tracker:tool.execute.after",
    "repo-overview-injector:tool.execute.after",
    "internal:governance-post-tool:tool.execute.after",
    "internal:user-memory:tool.execute.after",
    "internal:org-memory:tool.execute.after",
    "context-window-governor:tool.execute.after",
    "comment-checker:tool.execute.after",
    "directory-agents-injector:tool.execute.after",
    "directory-readme-injector:tool.execute.after",
    "rules-injector:tool.execute.after",
    "empty-task-response-detector:tool.execute.after",
    "delegation-nudge-agent-usage:tool.execute.after",
    "delegation-nudge-category-skill:tool.execute.after",
    "interactive-bash-session:tool.execute.after",
    "edit-failure-guidance:tool.execute.after",
    "delegation-failure-guidance:tool.execute.after",
    "internal:task-resume-info:tool.execute.after",
    "session-handoff:tool.execute.after",
    "swarm-agent:tool.execute.after",
    "internal:output-finalization:tool.execute.after",
  ],
  event: [
    "work-orchestrator:event",
    "auto-update-checker:event",
    "bridge:claude-code-hooks:event",
    "background-notification:event",
    "session-notification:event",
    "task-auto-continuation:event",
    "unstable-agent-watchdog:event",
    "pre-completion-verification:event",
    "sisyphus-contextual-injector:event",
    "internal:user-memory:event",
    "internal:org-memory:event",
    "runtime-tracker:event",
    "repo-overview-injector:event",
    "context-window-governor:event",
    "directory-agents-injector:event",
    "directory-readme-injector:event",
    "rules-injector:event",
    "think-mode:event",
    "delegation-nudge-agent-usage:event",
    "delegation-nudge-category-skill:event",
    "interactive-bash-session:event",
    "ralph-loop:event",
    "conditional-rules:event",
    "session-handoff:event",
    "tmux-parallel-agents:event",
    "swarm-agent:event",
    "internal:core-session-state:event",
    "internal:session-state-repair:event",
  ],
  "experimental.chat.messages.transform": [
    "internal:context-injector:experimental.chat.messages.transform",
    "thinking-block-validator:experimental.chat.messages.transform",
  ],
  "experimental.session.compacting": [
    "bridge:claude-code-hooks:experimental.session.compacting",
    "context-window-governor:experimental.session.compacting",
  ],
}
