export {
  OhMyOpenCodeConfigSchema,
  AgentOverrideConfigSchema,
  AgentOverridesSchema,
  McpNameSchema,
  AgentNameSchema,
  HookNameSchema,
  BuiltinCommandNameSchema,
  SisyphusAgentConfigSchema,
  SessionStateRepairConfigSchema,
  ToolOutputTruncatorConfigSchema,
  DynamicContextPruningConfigSchema,
  ContextWindowGovernorConfigSchema,
  CacheStrategyConfigSchema,
  CacheStrategyProviderPolicyModeSchema,
  CacheStrategyPrefixStabilityModeSchema,
  RalphLoopConfigSchema,
  ContinuationControlConfigSchema,
  ContinuationControlPrioritySchema,
  DEFAULT_CONTINUATION_CONTROL_CONFIG,
  WorkOrchestratorConfigSchema,
  DEFAULT_WORK_ORCHESTRATOR_CONFIG,
  GovernanceConfigSchema,
  GovernanceToolCriticalitySchema,
} from "./schema"
export { CURRENT_CONFIG_VERSION } from "./version"
export {
  validateStrictOhMyOpenCodeConfig,
  type StrictConfigValidationResult,
} from "./strict-config-validation"

export type {
  OhMyOpenCodeConfig,
  AgentOverrideConfig,
  AgentOverrides,
  McpName,
  AgentName,
  HookName,
  BuiltinCommandName,
  SisyphusAgentConfig,
  SessionStateRepairConfig,
  ToolOutputTruncatorConfig,
  DynamicContextPruningConfig,
  ContextWindowGovernorConfig,
  CacheStrategyConfig,
  CacheStrategyProviderPolicyMode,
  CacheStrategyPrefixStabilityMode,
  RalphLoopConfig,
  ContinuationControlConfig,
  ContinuationControlPriority,
  WorkOrchestratorConfig,
  GovernanceConfig,
  GovernanceToolCriticality,
} from "./schema"
